### ISSUE TITLE
which sample file here is responsible for process payments for credit cards or paypal?

### ISSUE THREAD

**Issue by Alfraganus** [capitalist-net/php-api-samples#2]
I need to integrate payment systems to our application but here in sample files, I could not find which one is responsible for all world payment gateway systems

**Comment by capitalist-net** [comment]
> I need to integrate payment systems to our application but here in sample files, I could not find which one is responsible for all world payment gateway systems

Hello! We don't have paypal support at this time. Payments to credit cards are available by using WORLDCARD opcode in mass payment file. List of all available systems you can find here https://capitalist.net/developers/api/page/batch-format?lang=en

**Comment by Alfraganus** [comment]
thank you, can I have sandbox test mode ?
